// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bolsa_de_trabajo.Models;

#nullable disable

namespace bolsa_de_trabajo.Migrations
{
    [DbContext(typeof(GOES_DBContext))]
    partial class GOES_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bolsa_de_trabajo.Models.Candidates", b =>
                {
                    b.Property<int>("IdCandidates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidates"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdCandidates");

                    b.HasIndex("JobId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("bolsa_de_trabajo.Models.Jobs", b =>
                {
                    b.Property<int>("IdJobs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJobs"));

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdJobs");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("bolsa_de_trabajo.Models.SelectorAgent", b =>
                {
                    b.Property<int>("IdCandidates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidates"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("jobsIdJobs")
                        .HasColumnType("int");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdCandidates");

                    b.HasIndex("jobsIdJobs");

                    b.ToTable("SelectorAgent");
                });

            modelBuilder.Entity("bolsa_de_trabajo.Models.Candidates", b =>
                {
                    b.HasOne("bolsa_de_trabajo.Models.Jobs", "Jobs")
                        .WithMany("Candidates")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("bolsa_de_trabajo.Models.SelectorAgent", b =>
                {
                    b.HasOne("bolsa_de_trabajo.Models.Jobs", "jobs")
                        .WithMany("Agents")
                        .HasForeignKey("jobsIdJobs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("jobs");
                });

            modelBuilder.Entity("bolsa_de_trabajo.Models.Jobs", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
