// <auto-generated />
using System;
using GOES.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GOES.API.Migrations
{
    [DbContext(typeof(GoesDbContext))]
    [Migration("20240919234633_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GOES.API.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidatoCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoCodigo");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("GOES.API.Models.Candidato", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("GOES.API.Models.HojaDeVida", b =>
                {
                    b.Property<string>("CandidatoCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExperienciaProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormacionAcademica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idiomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciasPersonales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidatoCodigo");

                    b.ToTable("HojaDeVida");
                });

            modelBuilder.Entity("GOES.API.Models.Bitacora", b =>
                {
                    b.HasOne("GOES.API.Models.HojaDeVida", "HojaDeVida")
                        .WithMany("Bitacoras")
                        .HasForeignKey("CandidatoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaDeVida");
                });

            modelBuilder.Entity("GOES.API.Models.HojaDeVida", b =>
                {
                    b.HasOne("GOES.API.Models.Candidato", "Candidato")
                        .WithOne("HojaDeVida")
                        .HasForeignKey("GOES.API.Models.HojaDeVida", "CandidatoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("GOES.API.Models.Candidato", b =>
                {
                    b.Navigation("HojaDeVida")
                        .IsRequired();
                });

            modelBuilder.Entity("GOES.API.Models.HojaDeVida", b =>
                {
                    b.Navigation("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
